name: 'devcontainer build and push' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from github
        uses: actions/checkout@v3
      - name: extract the github reference
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Docker Login LCAS
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: lcas.lincoln.ac.uk
          username: ${{ secrets.LCAS_REGISTRY_PUSHER }}
          password: ${{ secrets.LCAS_REGISTRY_TOKEN }}  
      - name: "image name from repo name"
        id: docker_image_name
        run: echo "docker_image=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' |sed 's/[^0-9,a-z,A-Z,=,_,\/]/-/g' >>${GITHUB_OUTPUT}
      - name: Build and push dev container
        if: ${{ github.event_name != 'pull_request' }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: lcas.lincoln.ac.uk/devcontainer/${{ steps.docker_image_name.outputs.docker_image }}
          push: always
          imageTag: latest
      - name: Build dev container task
        if: ${{ github.event_name == 'pull_request' }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: lcas.lincoln.ac.uk/devcontainer/${{ steps.docker_image_name.outputs.docker_image }}
          push: never
          imageTag: latest
  